In [1]:
import matplotlib.pyplot as plt
from scipy.linalg import expm
import numpy as np
import pprint
import math
import random

np.set_printoptions(precision=5)
pp = pprint.PrettyPrinter(indent=4)

In [2]:
# Task 1
P = np.array([[0, 0.8, 0.2, 0],
              [0, 0, 0.7, 0.3],
              [0, 0, 0, 1],
              [1, 0, 0, 0]])

for i in range(0, 200):
    print("Probability distribution on step", i, ':\n')
    pp.pprint(np.linalg.matrix_power(P, i))
    print("."*50, '\n')

distribution on step 128 :

array([[0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ]])
.................................................. 

The probability distribution on step 129 :

array([[0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ]])
.................................................. 

The probability distribution on step 130 :

array([[0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ]])
.................................................. 

The probability distribution on step 131 :

array([[0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
   

In [3]:
# Task 2

Q = np.array([[-1, 0.8, 0.2, 0],
              [0, -1, 0.7, 0.3],
              [0, 0, -1, 1],
              [1, 0, 0, -1]])

print("Probability distribution:\n")           
expm(Q * 1000)

Probability distribution:



array([[0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ],
       [0.2809 , 0.22472, 0.21348, 0.2809 ]])

In [4]:
# Task 3
def exp_rand(lambd):
  r = random.random()
  y  = -(1/lambd)*np.log(r)
  return y

def change_state(current_state):
  r = random.random()
  if (current_state == 0):
    if (r <= 0.2):
      return 2
    else:
      return 1
  elif (current_state == 1):
    if (r <= 0.3):
      return 3
    else:
      return 2
  elif (current_state == 2):
    return 3
  else:
    return 0

tmax = 10**12
current_time = 0.0
soj_times = np.array([0.0, 0.0, 0.0, 0.0])
q = np.array([1, 1, 1, 1])
current_state = 0
soj_times[0] += exp_rand(q[0])
current_time = soj_times[0]

while (current_time <= tmax):
  current_state = change_state(current_state)
  soj_times[current_state] += exp_rand(q[current_state])
  current_time += soj_times[current_state]

print("Probability distribution:\n",soj_times/soj_times.sum())
print("Summary time:\n", current_time)

Probability distribution:
 [0.28102 0.22423 0.21333 0.28142]
Summary time:
 1000000326203.2598
